bot:
  authorized_users:
  - 6557640463
  auto_start: true
  command_timeout: 30
  token: 7789747238:AAFrad7uAYucP-2Vi1VmxOlMcKelLcaXS5M
permissions: {}
shortcuts:
  test:
    action: open_url
    args: []
    command: /test
    display_name: name
    path: https://vk.com
web:
  admin_password_hash: $2b$12$7XxC72kaeqazBXgcjBw5XOoJiCFUriEGjBBJlBeKWJLg8zH4uAKQ2
  admin_username: admin
  host: 127.0.0.1
  port: 5000
  secret_key: 446e3342f4a5cc4cbec85f42c9c736d99a002ee25f2cc0b45665c14d93065867
updates:
  enabled: true
  check_interval_minutes: 5
