bot:
  authorized_users:
  - 6557640463
  auto_start: false
  command_timeout: 30
  token: 7789747238:AAFrad7uAYucP-2Vi1VmxOlMcKelLcaXS5M
permissions: {}
shortcuts:

web:
  admin_password_hash: $2b$12$3g71.M9Xi/79iAqxqmDnkO51w8YbhY5TTWz8Jx/vE/1JVvEofItbu
  admin_username: emivite
  host: 127.0.0.1
  port: 5000
  secret_key: 462b5a563837b5176dfd8729cbcea2d9520e20d283e2939c0bc41d49e58a781a
